Repository betarixm/434project, pull requests merged in 2023-11, with the labels that each got.

#24 Master Proposal
  docs/proposal-master.md
Labels: documentation, design

#23 Worker Proposal
  docs/proposal-master.md
  docs/proposal-worker.md
Labels: documentation, design

#25 RPC Protocol Proposal
  docs/proposal-rpc-protocol.md
Labels: documentation, design

#37 Progress Report 02
  docs/report-progress-02.md
Labels: documentation

#43 Define Type Aliases
  core/src/main/scala/MasterMetadata.scala
  core/src/main/scala/Node.scala
  core/src/main/scala/WorkerMetadata.scala
  core/src/main/scala/package.scala
Labels: feature

#42 File Binding of `Block`
  core/src/main/scala/Block.scala
  core/src/main/scala/Record.scala
  core/src/test/resources/block-spec-8.raw
  core/src/test/scala/BlockSpec.scala
  core/src/test/scala/RecordSpec.scala
Labels: feature

#45 Partition and Merge over `Block`
  core/src/main/scala/Block.scala
  core/src/main/scala/Key.scala
  core/src/test/scala/BlockSpec.scala
  core/src/test/scala/KeySpec.scala
Labels: feature

#44 Sort and Sample over Block
  core/src/main/scala/Block.scala
  core/src/main/scala/Key.scala
  core/src/main/scala/Record.scala
  core/src/test/scala/BlockSpec.scala
  core/src/test/scala/KeySpec.scala
Labels: feature

#56 Progress Report 03
  docs/report-progress-03.md
Labels: documentation

#57 Iteration 03
  .github/workflows/ci.yml
  build.sbt
  core/build.sbt
  core/src/main/scala/Block.scala
  core/src/main/scala/Key.scala
  core/src/main/scala/Main.scala
  core/src/main/scala/MasterMetadata.scala
  core/src/main/scala/Node.scala
  core/src/main/scala/Record.scala
  core/src/main/scala/WorkerMetadata.scala
  core/src/main/scala/package.scala
  core/src/test/resources/block-spec-8.raw
  core/src/test/scala/BlockSpec.scala
  core/src/test/scala/KeySpec.scala
  core/src/test/scala/RecordSpec.scala
  docs/deck-progress-presentation-01.pdf
  docs/report-progress-03.md
  master/build.sbt
  master/src/main/scala/Main.scala
  rpc/build.sbt
  rpc/src/main/scala/Main.scala
  utils/build.sbt
  utils/src/main/scala/Main.scala
  worker/build.sbt
  worker/src/main/scala/Main.scala
Labels: deploy

#60 Support ScalaPB
  build.sbt
  project/scalapb.sbt
  rpc/src/main/protobuf/hello.proto
Labels: feature

#58 Refactor `KeyRange` related things
  core/src/main/scala/Block.scala
  core/src/main/scala/KeyRange.scala
  core/src/main/scala/package.scala
  core/src/test/scala/BlockSpec.scala
Labels: refactor

#59 Write Defenitions of Protobufs
  rpc/src/main/protobuf/exchange.proto
  rpc/src/main/protobuf/hello.proto
  rpc/src/main/protobuf/master.proto
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/scala/ExchangeClient.scala
  rpc/src/main/scala/ExchangeServer.scala
  rpc/src/main/scala/MasterClient.scala
  rpc/src/main/scala/MasterServer.scala
  rpc/src/main/scala/WorkerClient.scala
  rpc/src/main/scala/WorkerServer.scala
  rpc/src/proto-file.proto
Labels: feature

#70 Refactor RPC specification
  build.sbt
  rpc/src/main/protobuf/common.proto
  rpc/src/main/protobuf/exchange.proto
  rpc/src/main/protobuf/hello.proto
  rpc/src/main/protobuf/master.proto
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/scala/ExchangeClient.scala
  rpc/src/main/scala/ExchangeServer.scala
  rpc/src/main/scala/MasterClient.scala
  rpc/src/main/scala/MasterServer.scala
  rpc/src/main/scala/WorkerClient.scala
  rpc/src/main/scala/WorkerServer.scala
  rpc/src/proto-file.proto
Labels: refactor

#72 Make `master` and `worker` depends on `rpc`
  build.sbt
Labels: bug

#71 Implement Master Server with Initialization Code
  master/src/main/scala/Main.scala
  rpc/src/main/scala/MasterClient.scala
  rpc/src/main/scala/MasterServer.scala
  worker/src/main/scala/Main.scala
Labels: feature

#73 feat: implement worker server
  rpc/src/main/scala/WorkerServer.scala
Labels: feature

#82 Progress Report 05
  docs/report-progress-05.md
Labels: documentation

#83 Iteration 05
  build.sbt
  docs/report-progress-05.md
  master/src/main/scala/Main.scala
  rpc/src/main/protobuf/common.proto
  rpc/src/main/protobuf/exchange.proto
  rpc/src/main/protobuf/hello.proto
  rpc/src/main/protobuf/master.proto
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/scala/ExchangeClient.scala
  rpc/src/main/scala/ExchangeServer.scala
  rpc/src/main/scala/MasterClient.scala
  rpc/src/main/scala/MasterServer.scala
  rpc/src/main/scala/WorkerClient.scala
  rpc/src/main/scala/WorkerServer.scala
  rpc/src/proto-file.proto
  worker/src/main/scala/Main.scala
Labels: deploy

#84 Progress Presentation 02
  docs/deck-progress-presentation-02.pdf
Labels: documentation

#85 Minimal PoC
  .dockerignore
  build.sbt
  core/src/main/resources/log4j2.properties
  core/src/main/scala/Block.scala
  core/src/main/scala/Key.scala
  core/src/main/scala/Record.scala
  core/src/test/scala/BlockSpec.scala
  docker-compose.yml
  docker/master/Dockerfile
  docker/worker/Dockerfile
  docker/worker/data/0/0
  docker/worker/data/0/1
  docker/worker/data/1/2
  docker/worker/data/1/3
  docker/worker/data/2/4
  docker/worker/data/2/5
  log4j2.properties
  master/src/main/resources/log4j2.properties
  master/src/main/scala/Main.scala
  master/src/main/scala/Master.scala
  master/src/main/scala/MasterArguments.scala
  rpc/src/main/protobuf/exchange.proto
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/resources/log4j2.properties
  rpc/src/main/scala/ExchangeClient.scala
  rpc/src/main/scala/ExchangeServer.scala
  rpc/src/main/scala/Implicit.scala
  rpc/src/main/scala/Main.scala
  rpc/src/main/scala/MasterClient.scala
  rpc/src/main/scala/MasterServer.scala
  rpc/src/main/scala/MasterService.scala
  rpc/src/main/scala/WorkerClient.scala
  rpc/src/main/scala/WorkerServer.scala
  rpc/src/main/scala/WorkerService.scala
  utils/src/main/resources/log4j2.properties
  utils/src/main/scala/GenericBuildFrom.scala
  utils/src/main/scala/MutableState.scala
  worker/src/main/resources/log4j2.properties
  worker/src/main/scala/Main.scala
  worker/src/main/scala/Worker.scala
  worker/src/main/scala/WorkerArguments.scala
Labels: enhancement, feature, refactor

#86 Parallel logics
  core/src/main/scala/Block.scala
  core/src/test/scala/BlockSpec.scala
  rpc/src/main/scala/WorkerService.scala
Labels: feature

#87 Minimal PoC
  core/src/main/scala/Block.scala
  core/src/main/scala/Key.scala
  docker-compose.yml
  docker/worker/Dockerfile
  docker/worker/data/0/0/1
  docker/worker/data/0/0/2
  docker/worker/data/0/1/1
  docker/worker/data/0/1/2
  docker/worker/data/1/0/1
  docker/worker/data/1/0/2
  docker/worker/data/1/1/1
  docker/worker/data/1/1/2
  docker/worker/data/1/3
  docker/worker/data/2/0/1
  docker/worker/data/2/0/2
  docker/worker/data/2/1/1
  docker/worker/data/2/1/2
  docker/worker/data/2/4
  docker/worker/data/2/5
  master/src/main/scala/Master.scala
  rpc/src/main/scala/WorkerService.scala
  worker/src/main/scala/WorkerArguments.scala
Labels: bug, enhancement

#88 Delete Original Input File
  worker/src/main/scala/WorkerService.scala
Labels: bug

#99 Progress Report 06
  docs/report-progress-06.md
Labels: documentation

#100 Iteration 06
  .dockerignore
  build.sbt
  core/src/main/resources/log4j2.properties
  core/src/main/scala/Block.scala
  core/src/main/scala/Key.scala
  core/src/main/scala/Record.scala
  core/src/test/scala/BlockSpec.scala
  count-line.bash
  docker-compose.yml
  docker/master/Dockerfile
  docker/worker/Dockerfile
  docker/worker/data/0/0/1
  docker/worker/data/0/0/2
  docker/worker/data/0/1/1
  docker/worker/data/0/1/2
  docker/worker/data/1/0/1
  docker/worker/data/1/0/2
  docker/worker/data/1/1/1
  docker/worker/data/1/1/2
  docker/worker/data/2/0/1
  docker/worker/data/2/0/2
  docker/worker/data/2/1/1
  docker/worker/data/2/1/2
  docs/deck-progress-presentation-02.pdf
  docs/report-progress-06.md
  gensort.bash
  log4j2.properties
  master/src/main/resources/log4j2.properties
  master/src/main/scala/Main.scala
  master/src/main/scala/Master.scala
  master/src/main/scala/MasterArguments.scala
  master/src/main/scala/MasterService.scala
  rpc/src/main/protobuf/exchange.proto
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/resources/log4j2.properties
  rpc/src/main/scala/ExchangeClient.scala
  rpc/src/main/scala/ExchangeServer.scala
  rpc/src/main/scala/GrpcServer.scala
  rpc/src/main/scala/Implicit.scala
  rpc/src/main/scala/Main.scala
  rpc/src/main/scala/MasterClient.scala
  rpc/src/main/scala/MasterServer.scala
  rpc/src/main/scala/WorkerClient.scala
  rpc/src/main/scala/WorkerServer.scala
  utils/src/main/resources/log4j2.properties
  utils/src/main/scala/GenericBuildFrom.scala
  utils/src/main/scala/MutableState.scala
  worker/src/main/resources/log4j2.properties
  worker/src/main/scala/Main.scala
  worker/src/main/scala/Worker.scala
  worker/src/main/scala/WorkerArguments.scala
  worker/src/main/scala/WorkerService.scala
Labels: deploy
