Repository betarixm/434project, pull requests merged in 2023-12, with the labels that each got.

#102 Refactor scripts
  bin/gensort
  bin/valsort
  count-line.bash
  gensort.bash
  scripts/count-line.sh
  scripts/gensort.sh
Labels: refactor

#101 Make worker use FixedThreadPool
  log4j2.properties
  worker/src/main/scala/WorkerService.scala
Labels: bug

#103 Packaging
  .github/workflows/ci.yml
  bin/master
  bin/worker
  build.sbt
  docker/master/Dockerfile
  docker/worker/Dockerfile
  project/plugins.sbt
Labels: deploy

#104 Remove unused files
  core/src/main/scala/Main.scala
  utils/src/main/scala/Main.scala
Labels: refactor

#107 Ensure non-loopback address
  utils/src/main/scala/Hooks.scala
Labels: bug

#106 Project clean up
  README.md
  log4j2.properties
Labels: documentation, enhancement

#110 Feat/exit logic
  worker/src/main/scala/Worker.scala
Labels: feature

#111 Package JARs with shell scripts
  .github/workflows/ci.yml
  .gitignore
  README.md
  bin/master
  bin/worker
  build.sbt
  build/.gitkeep
  docker/master/Dockerfile
  docker/worker/Dockerfile
Labels: enhancement

#112 Adjust Lifecycle of Executors
  master/src/main/scala/Master.scala
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/scala/GrpcServer.scala
  rpc/src/main/scala/WorkerClient.scala
  worker/src/main/scala/Worker.scala
  worker/src/main/scala/WorkerService.scala
Labels: bug

#113 Hotfix 121123
  .github/workflows/ci.yml
  .gitignore
  README.md
  bin/master
  bin/worker
  build.sbt
  build/.gitkeep
  docker/master/Dockerfile
  docker/worker/Dockerfile
  master/src/main/scala/Master.scala
  rpc/src/main/protobuf/worker.proto
  rpc/src/main/scala/GrpcServer.scala
  rpc/src/main/scala/WorkerClient.scala
  worker/src/main/scala/Worker.scala
  worker/src/main/scala/WorkerService.scala
Labels: bug, deploy

#114 Simulate tests using docker containers
  docker-compose.yml
  docker/master/Dockerfile
  docker/worker/Dockerfile
  docker/worker/data/0/0/1
  docker/worker/data/0/0/2
  docker/worker/data/0/1/1
  docker/worker/data/0/1/2
  docker/worker/data/1/0/1
  docker/worker/data/1/0/2
  docker/worker/data/1/1/1
  docker/worker/data/1/1/2
  docker/worker/data/2/0/1
  docker/worker/data/2/0/2
  docker/worker/data/2/1/1
  docker/worker/data/2/1/2
Labels: test

#115 Hotfix 121223
  docker-compose.yml
  docker/master/Dockerfile
  docker/worker/Dockerfile
  docker/worker/data/0/0/1
  docker/worker/data/0/0/2
  docker/worker/data/0/1/1
  docker/worker/data/0/1/2
  docker/worker/data/1/0/1
  docker/worker/data/1/0/2
  docker/worker/data/1/1/1
  docker/worker/data/1/1/2
  docker/worker/data/2/0/1
  docker/worker/data/2/0/2
  docker/worker/data/2/1/1
  docker/worker/data/2/1/2
Labels: bug

#116 Final Presentation
  docs/deck-final-presentation.pdf
Labels: documentation

#117 Hotfix 121423
  docs/deck-final-presentation.pdf
Labels: deploy
