Repository betarixm/434project, pull requests merged in 2023-10, with the labels that each got.

#15 Update Package Prefix
  README.md
  build.sbt
  src/main/scala/Main.scala
Labels: bug, documentation

#16 Architecture Proposal Suggestions
  docs/proposal-architecture.md
Labels: documentation, enhancement, design

#14 Setup Pre-commit Hooks
  .pre-commit-config.yaml
  README.md
  project/plugins.sbt
Labels: documentation, devops

#17 Document Coding Convention
  docs/convention.md
Labels: documentation

#18 Use markdownlint-cli2 on pre-commit hooks
  .pre-commit-config.yaml
Labels: devops

#19 Progress Report #01
  docs/report-progress-01.md
Labels: documentation

#21 Data Structure Proposal
  .markdownlint.json
  docs/proposal-data-structure.md
Labels: documentation, design
